# Generated by Django 4.2.1 on 2023-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
