# Generated by Django 4.2.1 on 2023-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customusermodel_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
