# Generated by Django 4.2.1 on 2023-05-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customusermodel_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='firstname',
        ),
    ]
