# Generated by Django 4.2.1 on 2023-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customusermodel_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
