# Generated by Django 4.2.1 on 2023-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customusermodel_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
