# Generated by Django 4.2.1 on 2023-05-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
